# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# メインのサンプルユーザーを1人作成する
User.create!(name:  "Example User",
             email: "example@railstutorial.org",
             password:              "aaaaaaaa",
             password_confirmation: "aaaaaaaa",
             activated: true,
             activated_at: Time.zone.now)

# 追加のユーザー
User.create!(name:  "太郎",
             email: "example1@railstutorial.org",
             password:              "aaaaaaaa",
             password_confirmation: "aaaaaaaa",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "太郎２号",
             email: "example2@railstutorial.org",
             password:              "aaaaaaaa",
             password_confirmation: "aaaaaaaa",
             activated: true,
             activated_at: Time.zone.now)

#ユーザーの投稿を作成
21.times do |i|
  users = User.order(:created_at).take(3)
  title = "タイトル#{i}"
  content = "コンテンツ#{i}" * 30
  users.each { |user| user.posts.create!(title: title, theme1: "テーマ１", theme2: "テーマ２", content: content) }
end

#ユーザーのお気に入り投稿を作成
posts = Post.all
user = User.first
favorite_posts = posts[1..15]
favorite_posts.each { |post| user.favorite(post) }


# 素材を作成
#メーカー系
Material.create!(theme: "食品")
Material.create!(theme: "農林")
Material.create!(theme: "水産")
Material.create!(theme: "建設")
Material.create!(theme: "住宅")
Material.create!(theme: "インテリア")
Material.create!(theme: "繊維")
Material.create!(theme: "化学")
Material.create!(theme: "薬品")
Material.create!(theme: "化粧品")
Material.create!(theme: "鉄鋼")
Material.create!(theme: "金属")
Material.create!(theme: "鉱業")
Material.create!(theme: "機械")
Material.create!(theme: "プラント")
Material.create!(theme: "電子・電気機器")
Material.create!(theme: "自動車")
Material.create!(theme: "輸送用機器")
Material.create!(theme: "医療機器")
Material.create!(theme: "印刷")
Material.create!(theme: "事務機器関連")
Material.create!(theme: "スポーツ")
Material.create!(theme: "玩具")

#小売
Material.create!(theme: "百貨店")
Material.create!(theme: "スーパー")
Material.create!(theme: "コンビニ")
Material.create!(theme: "専門店")

#金融
Material.create!(theme: "銀行")
Material.create!(theme: "証券")
Material.create!(theme: "クレジットカード")
Material.create!(theme: "信用販売")
Material.create!(theme: "リース")
Material.create!(theme: "保険")

#サービス・インフラ
Material.create!(theme: "不動産")
Material.create!(theme: "鉄道")
Material.create!(theme: "航空")
Material.create!(theme: "運輸")
Material.create!(theme: "物流")
Material.create!(theme: "電力")
Material.create!(theme: "ガス")
Material.create!(theme: "エネルギー")
Material.create!(theme: "フードサービス")
Material.create!(theme: "ホテル")
Material.create!(theme: "旅行")
Material.create!(theme: "医療")
Material.create!(theme: "福祉")
Material.create!(theme: "アミューズメント")
Material.create!(theme: "レジャー")
Material.create!(theme: "コンサルティング")
Material.create!(theme: "調査")
Material.create!(theme: "人材サービス")
Material.create!(theme: "教育")

Material.create!(theme: "代行")
Material.create!(theme: "レンタル")
Material.create!(theme: "フリーマーケット")
Material.create!(theme: "サプライズ")
Material.create!(theme: "共有")
Material.create!(theme: "コピー")
Material.create!(theme: "販売")
Material.create!(theme: "介護")
Material.create!(theme: "カウンセリング")
Material.create!(theme: "コミュニティ作成")
Material.create!(theme: "セキュリティ")
Material.create!(theme: "飲食")


#IT
Material.create!(theme: "ソフトウェア")
Material.create!(theme: "インターネット")
Material.create!(theme: "通信")

#広告・出版・マスコミ
Material.create!(theme: "放送")
Material.create!(theme: "新聞")
Material.create!(theme: "出版")
Material.create!(theme: "広告")

#官公庁・公社・団体
Material.create!(theme: "公社")
Material.create!(theme: "団体")
Material.create!(theme: "官公庁")

#その他
Material.create!(theme: "宿題")
Material.create!(theme: "謝罪")
Material.create!(theme: "墓参り")
Material.create!(theme: "命名")
Material.create!(theme: "恋人")
Material.create!(theme: "ストレス")
Material.create!(theme: "結婚")
Material.create!(theme: "葬儀")
Material.create!(theme: "ショッピング")
Material.create!(theme: "セミナー")
Material.create!(theme: "荷造り")
Material.create!(theme: "友達")
Material.create!(theme: "フラッシュモブ")
Material.create!(theme: "ホラー")
Material.create!(theme: "ゲーム")
Material.create!(theme: "本")
Material.create!(theme: "無料")
Material.create!(theme: "車")
Material.create!(theme: "サンタクロース")
Material.create!(theme: "ペット")
Material.create!(theme: "離婚")
Material.create!(theme: "赤ちゃん")
Material.create!(theme: "お金")
Material.create!(theme: "妊婦さん")
Material.create!(theme: "学生")
Material.create!(theme: "引っ越し")
Material.create!(theme: "人形")
Material.create!(theme: "趣味")
Material.create!(theme: "動物")
Material.create!(theme: "お酒")
Material.create!(theme: "アクセサリー")
Material.create!(theme: "トイレ")
Material.create!(theme: "自動販売機")
Material.create!(theme: "自然")
Material.create!(theme: "アダルト")
Material.create!(theme: "身体障害")
Material.create!(theme: "ファッション")
Material.create!(theme: "香り")
Material.create!(theme: "社会人")
Material.create!(theme: "バイク")
Material.create!(theme: "怪我")
Material.create!(theme: "イルミネーション")
Material.create!(theme: "アート")
Material.create!(theme: "通話")
Material.create!(theme: "リモート")
Material.create!(theme: "ロボット")
Material.create!(theme: "スピード")
Material.create!(theme: "レストラン")
Material.create!(theme: "LGBT")
Material.create!(theme: "学校")
Material.create!(theme: "ウィッグ")
Material.create!(theme: "宗教")
Material.create!(theme: "賃貸")
Material.create!(theme: "モデル")
Material.create!(theme: "料理")
Material.create!(theme: "マッチング")
Material.create!(theme: "個人")
Material.create!(theme: "録画")
Material.create!(theme: "故人")
Material.create!(theme: "遺骨")
Material.create!(theme: "陶器")
Material.create!(theme: "イケメン・美女")
Material.create!(theme: "ブサイク")
Material.create!(theme: "美容")
Material.create!(theme: "スマホ")
Material.create!(theme: "PC")
Material.create!(theme: "IT")
Material.create!(theme: "お坊さん")
Material.create!(theme: "クラウドソーシング")
Material.create!(theme: "高級")
Material.create!(theme: "安価")
Material.create!(theme: "デザイン")
Material.create!(theme: "暑さ・寒さ")
Material.create!(theme: "宇宙")
Material.create!(theme: "家族")
Material.create!(theme: "大切な人")
Material.create!(theme: "感動")
Material.create!(theme: "喜び")
Material.create!(theme: "悲しみ")
Material.create!(theme: "怒り")
Material.create!(theme: "驚き")
Material.create!(theme: "恐れ")
Material.create!(theme: "嫌悪")
Material.create!(theme: "娯楽")
Material.create!(theme: "飽きる")
Material.create!(theme: "共感")
Material.create!(theme: "夢中")
Material.create!(theme: "嫉妬")
Material.create!(theme: "興奮")
Material.create!(theme: "面白さ")
Material.create!(theme: "ロマンチック")
Material.create!(theme: "性")
Material.create!(theme: "プレゼント")
Material.create!(theme: "人気")
Material.create!(theme: "定額")
Material.create!(theme: "サブスクサービス")
Material.create!(theme: "放題")
Material.create!(theme: "暗闇")
Material.create!(theme: "民泊")
Material.create!(theme: "海外")
Material.create!(theme: "船")
Material.create!(theme: "仕入れ")
Material.create!(theme: "転売")
Material.create!(theme: "クラウド")
Material.create!(theme: "宅配")
Material.create!(theme: "パスポート")
Material.create!(theme: "添い寝")
Material.create!(theme: "清掃")
Material.create!(theme: "セルフ")
Material.create!(theme: "野菜")
Material.create!(theme: "健康")
Material.create!(theme: "ヴィーガン")
Material.create!(theme: "天然")
Material.create!(theme: "温泉")
Material.create!(theme: "ゴミ")
Material.create!(theme: "豪華")
Material.create!(theme: "派手")
Material.create!(theme: "地味")
Material.create!(theme: "普通")
Material.create!(theme: "汚い")
Material.create!(theme: "清潔")
Material.create!(theme: "ダンス")
Material.create!(theme: "音楽")
Material.create!(theme: "DJ")
Material.create!(theme: "エコ")
Material.create!(theme: "環境問題")
Material.create!(theme: "破壊")
Material.create!(theme: "想像")
Material.create!(theme: "漫画")
Material.create!(theme: "アニメ")
Material.create!(theme: "映画")
Material.create!(theme: "サブカルチャー")
Material.create!(theme: "VOD")
Material.create!(theme: "プラットフォーム")
Material.create!(theme: "電子化")
Material.create!(theme: "地図")
Material.create!(theme: "アプリ")
Material.create!(theme: "予約")
Material.create!(theme: "コミュニケーション")
Material.create!(theme: "写真")
Material.create!(theme: "SNS")
Material.create!(theme: "配信")
Material.create!(theme: "動画")
Material.create!(theme: "ストリーマー")
Material.create!(theme: "メモ")
Material.create!(theme: "タスク管理")
Material.create!(theme: "ネットサーフィン")
Material.create!(theme: "VR")
Material.create!(theme: "EC")
Material.create!(theme: "文字")
Material.create!(theme: "アパレル")
Material.create!(theme: "ハードウェア")
Material.create!(theme: "睡眠")
Material.create!(theme: "安全")
Material.create!(theme: "怠惰")
Material.create!(theme: "承認欲求")
Material.create!(theme: "心理")
Material.create!(theme: "メンタルヘルス")
Material.create!(theme: "筋トレ")
Material.create!(theme: "テレビ")
Material.create!(theme: "アイドル")
Material.create!(theme: "キャラクター")
Material.create!(theme: "デジタル")
Material.create!(theme: "アナログ")
Material.create!(theme: "グッズ")
Material.create!(theme: "家具・家電")
Material.create!(theme: "エンターテインメント")
Material.create!(theme: "お笑い")
Material.create!(theme: "かっこいい・可愛い")
Material.create!(theme: "若年")
Material.create!(theme: "中年")
Material.create!(theme: "老年")
Material.create!(theme: "学問")
Material.create!(theme: "プライベート")
Material.create!(theme: "職業")
Material.create!(theme: "政治")
Material.create!(theme: "芸能")
Material.create!(theme: "芸術")
Material.create!(theme: "女優・俳優")
Material.create!(theme: "プロゲーマー")
Material.create!(theme: "アナウンサー")
Material.create!(theme: "コスプレ")
Material.create!(theme: "季節イベント")
Material.create!(theme: "声優")
Material.create!(theme: "Youtube")
Material.create!(theme: "e-sports")
Material.create!(theme: "カードゲーム")
Material.create!(theme: "シンプル")
Material.create!(theme: "複雑")
Material.create!(theme: "ランキング")
Material.create!(theme: "ブログ")
Material.create!(theme: "ラジオ")
Material.create!(theme: "物語")
Material.create!(theme: "小説")
Material.create!(theme: "マジック")
Material.create!(theme: "工事")
Material.create!(theme: "簡略化")
Material.create!(theme: "ヨガ")
Material.create!(theme: "整体")
Material.create!(theme: "マッサージ")
Material.create!(theme: "レース")
Material.create!(theme: "花火")
Material.create!(theme: "四季")
Material.create!(theme: "脳トレ")
Material.create!(theme: "薬")
Material.create!(theme: "会員")
